development: &development
  adapter: postgresql
  encoding: unicode
  database: sample_haml_app_development
  pool: 5
  username: postgres
  password:
  min_messages: warning

test: &test
  <<: *development
  database: sample_hame_app_test<%= ENV['TEST_ENV_NUMBER'] %>
